### ISSUE TITLE
Internal test failure IE9: Object doesn't support property or method 'repeat'

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1604]
Test failure since https://github.com/qunitjs/qunit/commit/dfdfd43818fc62f61f3e1cc9a0ef709c604ea1a5

> [Windows 7, Internet Explorer 9.0] Error: "Edge cases" failed, `Died on test #2 undefined: Object doesn't support property or method 'repeat'`
> [Windows 7, Internet Explorer 9.0] Failed: 217 tests, 207 passed, 1 failed, 9 skipped; ran for 7586ms

Ref https://github.com/qunitjs/qunit/pull/1590, @smcclure15, @Krinkle.
