### PR TITLE
Polyfill String.repeat for IE test runs

### LINKED ISSUE #1604: Internal test failure IE9: Object doesn't support property or method 'repeat'
Test failure since https://github.com/qunitjs/qunit/commit/dfdfd43818fc62f61f3e1cc9a0ef709c604ea1a5

> [Windows 7, Internet Explorer 9.0] Error: "Edge cases" failed, `Died on test #2 undefined: Object doesn't support property or method 'repeat'`
> [Windows 7, Internet Explorer 9.0] Failed: 217 tests, 207 passed, 1 failed, 9 skipped; ran for 7586ms

Ref https://github.com/qunitjs/qunit/pull/1590, @smcclure15, @Krinkle.

### PR DESCRIPTION
**Pull request by smcclure15**
Resolves #1604

### CODE REVIEW

**Comment by Krinkle** [comment]
Thanks! 🙂
